### ISSUE TITLE
Arch card please :)

### ISSUE THREAD

**Issue by leobrowning92** [jstpcs/lnxpcs#1]
This is hardly an issue, as I know this is just your private work and you are not beholden to anyone to make more content, I would love to see an ubuntu and arch card :) Ive seen on reddit that arch is on your todo list, but I just wanted to lodge my interest here!

Whether you do or not, there is already so much cool stuff here. Thanks!

**Comment by shawniac** [comment]
Uhm... isn't there many designs available for [Arch](https://github.com/jstpcs/lnxpcs/tree/master/distro/arch) and [Ubuntu](https://github.com/jstpcs/lnxpcs/tree/master/distro/ubuntu) already? (less on ubuntu but still there is some).

Or did I get something wrong and "card" is a special design style?

**Comment by xeon-zolt** [comment]
i would also love to see arch in card style

**Comment by leobrowning92** [comment]
@shawniac there are heaps of arch and ubuntu designs but yea there is a specific style to all the designs in the cards folder that I think it would be great to see ubuntu (its pretty popular) and arch ( just my personal favorite at the moment) in that style.

**Comment by xeon-zolt** [comment]
arch would be like ace of the cards :smile:

**Comment by shawniac** [comment]
After understanding this issue properly and because I am using Archlinux myself, I can only second this. I heard there is even a Python-card underway, looking forward to those! 😄

**Comment by jstpcs** [comment]
Hi all. Thanks for this request. I also like Arch very much and made several attempts to make a Arch card but I'm not satisfied with the results yet. It's definitely in my list with high priority.

**Comment by KoolDude214** [comment]
Would love an arch card!

**Comment by jstpcs** [comment]
It took a dozen attempts, but finally the Arch card is [ready](https://github.com/jstpcs/lnxpcs/blob/7c253a5e22f983bf6a0a92868077d8624a0469c2/cards/arch-card.png).

**Comment by leobrowning92** [comment]
Couldn't be more happy! with it! Im going to print it out and put it on my office wall along with sudo and python!
