### ISSUE TITLE
Hoodie variants

### ISSUE THREAD

**Issue by KoolDude214** [jstpcs/lnxpcs#13]
Can we please have hoodie variants of everything in t shirts?

**Comment by jstpcs** [comment]
Not all designs look good on hoodies but I will try to make hoodies for some of them. May be there are some particular prints that you are interested in?

**Comment by KoolDude214** [comment]
It would be nice to have a hoodie with the tuxzilla design on it.

**Comment by jstpcs** [comment]
The link to hoodie with Tuxzilla is added to the [overview](https://linux.pictures/portfolio/non-distro/) page
