### ISSUE TITLE
Python card

### ISSUE THREAD

**Issue by shawniac** [jstpcs/lnxpcs#2]
I've read on reddit just now that a python card is in planning!

Looking forward to it! Can't wait!

Thanks for your work up until now and in the future! You're an awesome person!

**Comment by jstpcs** [comment]
Thank you very much. Yes, python card will definitely be created.

**Comment by jstpcs** [comment]
[Here](https://github.com/jstpcs/lnxpcs/blob/6544417fbeb48cf384d5016de476ef74790b140a/cards/python-card.png) is the Python card.

**Comment by jstpcs** [comment]
Python card is created
