### ISSUE TITLE
"rm -rf /" please!

### ISSUE THREAD

**Issue by jaxonpickett** [jstpcs/lnxpcs#22]
Need an image for the most destruction of all linux commands! (Love the work by the way!)

**Comment by jstpcs** [comment]
There are two images for the "rm -rf" - [1st](https://github.com/jstpcs/lnxpcs/blob/master/non-distro/scream.png), [2nd](https://github.com/jstpcs/lnxpcs/blob/master/non-distro/expecto-tux.png).
