### ISSUE TITLE
Tor Please?

### ISSUE THREAD

**Issue by JRyuzaki** [jstpcs/lnxpcs#24]
I just discovered your art and it is amazing. I love the cards. Do you think you could maybe create one for Tor?

**Comment by jstpcs** [comment]
Definitely yes. Tor deserves a card.

**Comment by jstpcs** [comment]
[Here](https://github.com/jstpcs/lnxpcs/blob/47fba6fdcf98ef8824636afe12d2f2e9bda2cb72/cards/tor-card.png) it is.
