### ISSUE TITLE
Card variation without banner and text?

### ISSUE THREAD

**Issue by ItsDaGeek** [jstpcs/lnxpcs#28]
Albeit, not for the purpose of cards, having a version sans-text can be useful for use in a minimal work, or in my case, creating a vinyl cut for walls.

Thanks,

**Comment by jstpcs** [comment]
I think that it's possible to create a version without a border but nor without the text. Will it be ok for you?

**Comment by jstpcs** [comment]
Issue closed as no answer from reported.
