### ISSUE TITLE
Link to your main page instead

### ISSUE THREAD

**Issue by shawniac** [jstpcs/lnxpcs#3]
Instead of linking to each "product" individually I'd rather have a link to https://teespring.com/stores/best-linux-tees and browse your stuff there. This is because I can then immediately see the designs and not have to open several tabs and go back and forth way too often, imho.

**Comment by shawniac** [comment]
Or any other gallery where we can browse design more easily and possibly with an overview, where you can see as many designs as possible on a single "page".

**Comment by jstpcs** [comment]
Thank for this proposal. Actually the link you mention is not main page and I don't like it as there is a mess. I will try to create a way to preview the images, but a bit later. Currently you can clone the repo and if you like any image, you can use it's name to search through readme file.
