### ISSUE TITLE
EU version of cron-card-black, kill-card-black-c, obey-sudo-red

### ISSUE THREAD

**Issue by devurandom** [jstpcs/lnxpcs#31]
I would like to buy the following from the EU:
* cron-card-black
* kill-card-black-c
* obey-sudo-red

Could you please create an EU variant of them (with reduced shipping), as you did with highway-bash-eu for highway-bash?

**Comment by jstpcs** [comment]
Sure. Here you can get [sudo](https://teespring.com/obey-sudo-red-eu), [cron](https://teespring.com/cron-card-black-eu) and [kill](https://teespring.com/kill-card-black-c-eu).

**Comment by devurandom** [comment]
Thanks a lot!

* The US version has multiple shirt colours for the sudo motif. Would that also be possible for the EU version?
* highway-bash-eu has an organic variant. Would that also be available for the other shirts listed above?

**Comment by jstpcs** [comment]
Unfortunately the EU apparel has much less options. Sorry.

**Comment by devurandom** [comment]
The organic variant, that you offer for highway-bash-eu, is also not possible for the other shirts?

**Comment by jstpcs** [comment]
Just received answer from their support, all is possible and that was my mistake. Please just list what tees and what colors you need I will recreate the objects.

**Comment by jstpcs** [comment]
Here are the updated links for you with multiple colors and organic options. 

- [sudo](https://teespring.com/obey-sudo-red-eu-organic#pid=389&cid=100029&sid=front)
- [cron](https://teespring.com/cron-card-black-eu-organic#pid=389&cid=100029&sid=front)
- [kill](https://teespring.com/kill-card-black-c-eu-organic#pid=389&cid=100029&sid=front)
