### ISSUE TITLE
Could GCC join the game ?

### ISSUE THREAD

**Issue by nelker** [jstpcs/lnxpcs#33]
Really outstanding work !

It would be great to have a card for the program that made FOSS expansion possible.
GCC's [logo](https://upload.wikimedia.org/wikipedia/commons/a/af/GNU_Compiler_Collection_logo.svg) is a gnu breaking out of an egg, but maybe you have another symbolism in mind.

**Comment by jstpcs** [comment]
here you are - [white](https://github.com/jstpcs/lnxpcs/blob/45a0c16d31f3845e095096043847c54dadafe6ed/cards/classic/gcc-card.png) and [dark](https://github.com/jstpcs/lnxpcs/blob/45a0c16d31f3845e095096043847c54dadafe6ed/cards/black/gcc-card-black.png)

**Comment by nelker** [comment]
Very nice, thank you ^^
