### ISSUE TITLE
Vim?

### ISSUE THREAD

**Issue by CrixuAMG** [jstpcs/lnxpcs#34]
Amazed to see it hasn't been suggested yet, but ok.

**Comment by jstpcs** [comment]
i think that not only vim but also the shortcut for exiting it deserves a [pic](https://github.com/jstpcs/lnxpcs/blob/a2173b06767e1170c935ff144d9b2d2c5bdc31bb/non-distro/vim-shortcut.png)

**Comment by CrixuAMG** [comment]
Wow, that looks amazing. Will definitely be ordering some items with this design! Thanks!
