### ISSUE TITLE
Periodic table - some errors

### ISSUE THREAD

**Issue by ashmonger** [jstpcs/lnxpcs#37]
I've seen some errors about the periodic table:

* Debian should be yellow, or yellow with something to make it the root distro.
* Scientific Linux is based on redhat/centos
* Xubuntu/Ubuntu Gnome should be yellow
* Kali Linux, Knoppix are Debian based, so yellow
* Gentoo Linux is green, but Sabayon is orange (gentoo based)

**Comment by jstpcs** [comment]
[fixed](https://github.com/jstpcs/lnxpcs/commit/202a58bef05d2bf6ddc1c8028032290060e6a291)
