### ISSUE TITLE
[Periodic table] Latest stable year is wrong for NixOS

### ISSUE THREAD

**Issue by jpotier** [jstpcs/lnxpcs#38]
This poster is fantastic, very nice idea! I really love it, I think I'll have it laser printed on my next keyboard : )

However, nixOS (63) latest stable is 2017.03 (pretty soon 2017.09). On the poster it is listed as 2.014, which is pretty old.

**Comment by jstpcs** [comment]
it's not the latest stable, but the year when the first stable appeared and it should be 2.003 in this case. thanks for reporting.

**Comment by jpotier** [comment]
Ah : ) My bad! Thanks for correcting it!
