### ISSUE TITLE
Solus please?

### ISSUE THREAD

**Issue by Dizeeee** [jstpcs/lnxpcs#4]
I love Solus and would love to see you make art based on it!

**Comment by lunix4all** [comment]
Seconded. That awesome ship logo and budgie are perfect for a cards restyle!

**Comment by jstpcs** [comment]
[Here](https://github.com/jstpcs/lnxpcs/commit/9455bb51d14c0bc79d34a2199285ac1d485be6a0) it is.

**Comment by lunix4all** [comment]
Thanks! Great job as always!
