### ISSUE TITLE
Wallpaper sizes

### ISSUE THREAD

**Issue by johnramsden** [jstpcs/lnxpcs#41]
I would love to see some of the cards and wallpaper sizes, even if that just means expanding the background color to be the right dimensions. I love the different cards and would like to use them as wallpaper but they either have to be centered, or altered to be used.

**Comment by danielquinn** [comment]
Actually, there's a script to do just that for any or all of the images: https://linux.pictures/wallpaper

**Comment by jstpcs** [comment]
@johnramsden, as there are a lot of different possible resolutions, i decided not to create wallpapers, but provide a script that everybody can use and create wallpapers in linux way. please use the link provided above (thanks @danielquinn ) to see the script and example.

**Comment by johnramsden** [comment]
@danielquinn @jstpcs Ooooo, nice!

**Comment by johnramsden** [comment]
@jstpcs What is the better way, i'm curious?

In the footer:
> this script is crap. i know the better way and will send you an [email](jstpcs@protonmail.com).

**Comment by jstpcs** [comment]
this is the link for those, who knows the better way and wants to send me improved script.
