### ISSUE TITLE
Linux Mint yoo

### ISSUE THREAD

**Issue by drkmrin78** [jstpcs/lnxpcs#45]
These cards are soo dope

**Comment by Piterden** [comment]
I checked dictionary. Do you mean drug or stupid person?

**Comment by drkmrin78** [comment]
Dope as in cool, or awesome

**Comment by jstpcs** [comment]
[ready](https://github.com/jstpcs/lnxpcs/commit/21c8f5ee1f67bb876d9c7b9be1bd0cb86ef9875b)

**Comment by drkmrin78** [comment]
Looks awesome! Love it!
