### ISSUE TITLE
Silly alternative request

### ISSUE THREAD

**Issue by ywum7fhv0skqh07h** [jstpcs/lnxpcs#47]
Can you please make an alternative of this one with Yoda Flossing? https://linux.pictures/projects/may-the-foss-be-with-you-jpg

**Comment by jstpcs** [comment]
[here](https://github.com/jstpcs/lnxpcs/blob/c047c09edbec3d3308a3cba25318edba4696a064/non-distro/may-the-floss.png) it is.
