### ISSUE TITLE
Request: Java

### ISSUE THREAD

**Issue by javacoldbrew** [jstpcs/lnxpcs#57]
If you have the time, I love to see a Java card design. Also, are you accepting donations? Or is there any way to support you?

**Comment by jstpcs** [comment]
yes, i think it's possible to create a java card. i do it just for fun and when have inspiration, so i didn't think about donations, anyway thank you for your intention.

**Comment by javacoldbrew** [comment]
Awesome, let me know if you ever start taking donations!

**Comment by jstpcs** [comment]
[ready](https://github.com/jstpcs/lnxpcs/commit/56716b78623050bbe0d5c114cebea46884a91bc1)

**Comment by javacoldbrew** [comment]
Thank you so much for making this! It looks amazing
