### ISSUE TITLE
Request: Rust

### ISSUE THREAD

**Issue by ctjhoa** [jstpcs/lnxpcs#63]
I'd love to see a Rust card. It's a very cool language with some unique features.

https://www.rust-lang.org/ for more details.

Here is some resources for inspiration:
https://devswag.com/products/rustconf-tote-bag
https://devswag.com/products/rust-t-shirt
http://www.rustacean.net/

**Comment by jstpcs** [comment]
[white](https://github.com/jstpcs/lnxpcs/blob/92f7cd8ece8177e6e457180a2c380d186843f219/cards/classic/rust-card.png) and [dark](https://github.com/jstpcs/lnxpcs/blob/92f7cd8ece8177e6e457180a2c380d186843f219/cards/black/rust-card-black.png)

**Comment by ctjhoa** [comment]
Awesome! Thank you very much.
