### ISSUE TITLE
Golang Please?

### ISSUE THREAD

**Issue by Munsio** [jstpcs/lnxpcs#7]
It would be great to see our beloved Gopher in your artstyle.

**Comment by jstpcs** [comment]
@Munsio here are the go cards - [white](https://github.com/jstpcs/lnxpcs/blob/13623317b4de9aa34a5f53f6dc36717a92a213f8/cards/classic/golang-card.png) and [black](https://github.com/jstpcs/lnxpcs/blob/13623317b4de9aa34a5f53f6dc36717a92a213f8/cards/black/golang-card-black.png)
